version: '3.9'

services:
    postgres:
        container_name: ${DATABASE_NAME}
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - ${DATABASE_PORT}:5432
            
      