version: '3.9'

services:
    postgres:
        container_name: ${DATABASE_NAME}
        image: postgres:latest
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        ports:
            - ${DATABASE_PORT}:5432

    api:
        build: .
        container_name: marvel_stone_api
        restart: unless-stopped
        ports: 
            - ${API_PORT}:3333
        command:
            - yarn start:prod
        depends_on: 
            - postgres
            
      